/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpgjava;

import javax.swing.JOptionPane;

/**
 *
 * @author rneox
 */
public class LoginRpg extends javax.swing.JFrame {

    /**
     * Creates new form LoginRpg
     */
    public LoginRpg() {
        initComponents();
    }
    String emailogin, senhalogin;
    String emailcli;
    String senhacli;
    private void limpaform(){
    txtemail.setText("");
    txtsenha.setText("");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlimpar = new javax.swing.JToggleButton();
        btncadastro = new javax.swing.JButton();
        Entrar = new javax.swing.JToggleButton();
        txtsenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Entrar1 = new javax.swing.JToggleButton();
        btnlimpar1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 80, -1));

        btncadastro.setText("Cadastro");
        btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btncadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        Entrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 80, -1));

        txtsenha.setBackground(new java.awt.Color(0, 0, 0));
        txtsenha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 140, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email :");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        txtemail.setBackground(new java.awt.Color(0, 0, 0));
        txtemail.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 140, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 110, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGOTIPOOOOOOOO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        Entrar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Entrar1.setText("Entrar");
        Entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 80, -1));

        btnlimpar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnlimpar1.setText("Limpar");
        btnlimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
       
        Cliente cliente1 = new Cliente(nome,email,senha);
        emailcli = cliente1.email;
        senhacli = cliente1.senha;

        
        JOptionPane.showMessageDialog(null, emailcli); 
        this.emailogin = txtemail.getText(); 
        char[] pass1 = txtsenha.getPassword();
        this.senhalogin = new String(pass1);
        
        
        
        
        if(emailogin.equals(emailcli) && senhalogin.equals(senhacli)){
        LojaRPG loja = new LojaRPG();
        LoginRpg telalogin = new LoginRpg();
        telalogin.setVisible(true); 
        dispose(); 
        }
        else if(emailogin == null || senhalogin == null){

        JOptionPane.showMessageDialog(null, "Informações incorretas"); 
        }
        else{
            JOptionPane.showMessageDialog(null, "Informações incorretas"); 
        }
        
    }//GEN-LAST:event_EntrarActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed

        limpaform();
    }//GEN-LAST:event_btnlimparActionPerformed

    private void Entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrar1ActionPerformed

    private void btnlimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpar1ActionPerformed

    private void btncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroActionPerformed
        
        Cadastrar formcad = new Cadastrar();
        formcad.setVisible(true); 
        dispose(); 
        
        
    }//GEN-LAST:event_btncadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JToggleButton Entrar;
    private javax.swing.JToggleButton Entrar1;
    private javax.swing.JButton btncadastro;
    private javax.swing.JToggleButton btnlimpar;
    private javax.swing.JToggleButton btnlimpar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
